import {
  UserProfile,
  SiteBranch,
  Incident,
  Checkpoint,
  PatrolScan,
  OBEntry,
  EquipmentItem,
  AuditLog,
  SecurityCompany,
  HouseUnit,
  RegisteredDevice,
} from './types';

export const INITIAL_COMPANIES: SecurityCompany[] = [
  {
    id: 'comp-aegis',
    name: 'Aegis Elite Protection Services',
    shortCode: 'AEGIS',
    region: 'Gauteng & Sandton Precinct',
    logo: '🛡️',
    supportPhone: '+27 11 900 3000',
    supportEmail: 'control@aegissec.co.za',
    planName: 'Enterprise Shield Tier',
    planLimitHouses: 50,
    maxDevicesPerHouse: 2,
    activeHousesCount: 18,
  },
  {
    id: 'comp-vanguard',
    name: 'Vanguard Tactical Response',
    shortCode: 'VNGRD',
    region: 'Western Cape & Atlantic Coast',
    logo: '⚡',
    supportPhone: '+27 21 440 2200',
    supportEmail: 'ops@vanguardtactical.za',
    planName: 'Enterprise Shield Tier',
    planLimitHouses: 50,
    maxDevicesPerHouse: 2,
    activeHousesCount: 12,
  },
  {
    id: 'comp-shieldcorp',
    name: 'ShieldCorp Armed Command',
    shortCode: 'SHLD',
    region: 'KZN & Umhlanga Coastal',
    logo: '🦅',
    supportPhone: '+27 31 888 1199',
    supportEmail: 'dispatch@shieldcorp.za',
    planName: 'Enterprise Shield Tier',
    planLimitHouses: 50,
    maxDevicesPerHouse: 2,
    activeHousesCount: 8,
  },
];

export const INITIAL_HOUSES: HouseUnit[] = [
  {
    id: 'hse-01',
    companyId: 'comp-aegis',
    siteId: 'site-sandton',
    houseNumber: 'Unit 14',
    streetAddress: '14 Maple Ridge, Rivonia Road, Sandton',
    residentName: 'Nomsa Dlamini',
    residentEmail: 'nomsa.dlamini@community.za',
    residentPhone: '+27 71 892 4110',
    status: 'active',
    joinedDate: '2026-01-15',
    coordinates: { lat: -26.1082, lng: 28.0573, address: 'Unit 14 Maple Ridge' },
    registeredDevices: [
      {
        id: 'dev-01',
        houseId: 'hse-01',
        deviceName: "Nomsa's iPhone 15 Pro (Mobile App)",
        deviceType: 'mobile_app',
        deviceUid: 'IMEI-8849-APP-01',
        registeredAt: '2026-01-15',
        lastActive: 'Just now',
        batteryPercent: 88,
        status: 'active',
      },
      {
        id: 'dev-02',
        houseId: 'hse-01',
        deviceName: 'Master Bedroom Wall Panic Keyfob',
        deviceType: 'iot_keyfob',
        deviceUid: 'FOB-RF915-02',
        registeredAt: '2026-01-18',
        lastActive: '2 hours ago',
        batteryPercent: 95,
        status: 'active',
      },
    ],
  },
  {
    id: 'hse-02',
    companyId: 'comp-aegis',
    siteId: 'site-sandton',
    houseNumber: 'Unit 08',
    streetAddress: '8 Jacaranda Lane, Sandhurst, Sandton',
    residentName: 'Thabo Ndlovu',
    residentEmail: 't.ndlovu@corporate.za',
    residentPhone: '+27 82 444 8811',
    status: 'active',
    joinedDate: '2026-02-01',
    coordinates: { lat: -26.1070, lng: 28.0560, address: '8 Jacaranda Lane' },
    registeredDevices: [
      {
        id: 'dev-03',
        houseId: 'hse-02',
        deviceName: 'Galaxy S24 Ultra Resident App',
        deviceType: 'mobile_app',
        deviceUid: 'IMEI-7712-APP-03',
        registeredAt: '2026-02-01',
        lastActive: '12 mins ago',
        batteryPercent: 74,
        status: 'active',
      },
      {
        id: 'dev-04',
        houseId: 'hse-02',
        deviceName: 'Guardhouse Perimeter Wireless Buzzer',
        deviceType: 'guard_terminal',
        deviceUid: 'TRM-9910-04',
        registeredAt: '2026-02-05',
        lastActive: '5 mins ago',
        batteryPercent: 100,
        status: 'active',
      },
    ],
  },
  {
    id: 'hse-03',
    companyId: 'comp-aegis',
    siteId: 'site-sandton',
    houseNumber: 'Unit 22',
    streetAddress: '22 Sunset Boulevard, Morningside',
    residentName: 'Brenda Jacobs',
    residentEmail: 'brenda.j@morningside.za',
    residentPhone: '+27 83 912 0044',
    status: 'active',
    joinedDate: '2026-02-10',
    coordinates: { lat: -26.1062, lng: 28.0588, address: '22 Sunset Blvd' },
    registeredDevices: [
      {
        id: 'dev-05',
        houseId: 'hse-03',
        deviceName: "Brenda's Pixel 9 Pro",
        deviceType: 'mobile_app',
        deviceUid: 'IMEI-9011-APP-05',
        registeredAt: '2026-02-10',
        lastActive: '1 hr ago',
        batteryPercent: 91,
        status: 'active',
      },
    ],
  },
  {
    id: 'hse-04',
    companyId: 'comp-aegis',
    siteId: 'site-sandton',
    houseNumber: 'Unit 03',
    streetAddress: '3 Oakridge Close, Inanda, Sandton',
    residentName: 'Francois Du Plessis',
    residentEmail: 'francois@inanda.za',
    residentPhone: '+27 82 555 4910',
    status: 'active',
    joinedDate: '2026-03-01',
    coordinates: { lat: -26.1090, lng: 28.0550, address: '3 Oakridge Close' },
    registeredDevices: [
      {
        id: 'dev-06',
        houseId: 'hse-04',
        deviceName: 'Gatekeeper Panic Station',
        deviceType: 'guard_terminal',
        deviceUid: 'TRM-8802-06',
        registeredAt: '2026-03-01',
        lastActive: 'Just now',
        batteryPercent: 100,
        status: 'active',
      },
      {
        id: 'dev-07',
        houseId: 'hse-04',
        deviceName: 'Mobile Family App Instance',
        deviceType: 'mobile_app',
        deviceUid: 'IMEI-3310-APP-07',
        registeredAt: '2026-03-04',
        lastActive: '20 mins ago',
        batteryPercent: 65,
        status: 'active',
      },
    ],
  },
  {
    id: 'hse-05',
    companyId: 'comp-aegis',
    siteId: 'site-sandton',
    houseNumber: 'Unit 19',
    streetAddress: '19 Willow Tree Estate, Sandton',
    residentName: 'Kwanele Khuzwayo',
    residentEmail: 'kwanele@willowtree.za',
    residentPhone: '+27 76 888 1209',
    status: 'active',
    joinedDate: '2026-03-12',
    coordinates: { lat: -26.1075, lng: 28.0570, address: '19 Willow Tree' },
    registeredDevices: [
      {
        id: 'dev-08',
        houseId: 'hse-05',
        deviceName: 'Living Room Rapid Beacon RF',
        deviceType: 'iot_keyfob',
        deviceUid: 'FOB-RF880-08',
        registeredAt: '2026-03-12',
        lastActive: '30 mins ago',
        batteryPercent: 99,
        status: 'active',
      },
    ],
  },
];

export const INITIAL_BRANCHES: SiteBranch[] = [
  {
    id: 'site-sandton',
    companyId: 'comp-aegis',
    name: 'Sandton Financial Precinct & Mall',
    region: 'Gauteng North',
    address: '83 Rivonia Road, Sandton, Johannesburg',
    coordinates: { lat: -26.1076, lng: 28.0567 },
    activeGuardsCount: 14,
    openIncidentsCount: 2,
    supervisorName: 'Kagiso Sithole',
    supervisorPhone: '+27 82 555 0192',
  },
  {
    id: 'site-waterfront',
    companyId: 'comp-aegis',
    name: 'V&A Marine & Retail Hub',
    region: 'Western Cape Coastal',
    address: '19 Dock Road, Victoria & Alfred Waterfront, Cape Town',
    coordinates: { lat: -33.9056, lng: 18.4217 },
    activeGuardsCount: 18,
    openIncidentsCount: 1,
    supervisorName: 'David Van Der Merwe',
    supervisorPhone: '+27 83 444 8821',
  },
  {
    id: 'site-umhlanga',
    companyId: 'comp-aegis',
    name: 'Umhlanga Ridge Tech Park',
    region: 'KZN Metro',
    address: '14 Palm Boulevard, Umhlanga Rocks, Durban',
    coordinates: { lat: -29.7245, lng: 31.0662 },
    activeGuardsCount: 9,
    openIncidentsCount: 0,
    supervisorName: 'Thabo Mokoena',
    supervisorPhone: '+27 81 333 7710',
  },
  {
    id: 'site-centurion',
    companyId: 'comp-aegis',
    name: 'Centurion Logistics Hub',
    region: 'Gauteng South',
    address: '45 Old Johannesburg Road, Centurion',
    coordinates: { lat: -25.8603, lng: 28.1894 },
    activeGuardsCount: 11,
    openIncidentsCount: 0,
    supervisorName: 'Pieter Botha',
    supervisorPhone: '+27 84 999 1234',
  },
];

export const CURRENT_USERS: Record<string, UserProfile> = {
  community: {
    id: 'usr-comm-01',
    name: 'Nomsa Dlamini',
    role: 'community',
    phone: '+27 71 892 4110',
    email: 'nomsa.dlamini@community.za',
    siteId: 'site-sandton',
    siteName: 'Sandton Financial Precinct & Mall',
    companyId: 'comp-aegis',
    companyName: 'Aegis Elite Protection Services',
    assignedHouseId: 'hse-01',
    assignedDeviceId: 'dev-01',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  guard: {
    id: 'usr-guard-01',
    name: 'Officer Sipho Khumalo',
    role: 'guard',
    badgeNumber: 'SEC-8842',
    callSign: 'Alpha-1 Response',
    phone: '+27 76 342 9012',
    email: 's.khumalo@aegissec.co.za',
    siteId: 'site-sandton',
    siteName: 'Sandton Financial Precinct & Mall',
    companyId: 'comp-aegis',
    companyName: 'Aegis Elite Protection Services',
    assignedDeviceId: 'dev-04',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  supervisor: {
    id: 'usr-sup-01',
    name: 'Supervisor Kagiso Sithole',
    role: 'supervisor',
    badgeNumber: 'SUP-401',
    callSign: 'Command-Sandton',
    phone: '+27 82 555 0192',
    email: 'k.sithole@aegissec.co.za',
    siteId: 'site-sandton',
    siteName: 'Sandton Financial Precinct & Mall',
    companyId: 'comp-aegis',
    companyName: 'Aegis Elite Protection Services',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  admin: {
    id: 'usr-adm-01',
    name: 'Elena Rostova',
    role: 'admin',
    badgeNumber: 'SYS-ADMIN-01',
    phone: '+27 11 900 3000',
    email: 'elena.rostova@aegissec.co.za',
    siteId: 'site-sandton',
    siteName: 'HQ Corporate Control',
    companyId: 'comp-aegis',
    companyName: 'Aegis Elite Protection Services',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  manager: {
    id: 'usr-mgr-01',
    name: 'Col. Marcus Vance',
    role: 'manager',
    badgeNumber: 'OPS-MGR-07',
    phone: '+27 82 111 9900',
    email: 'marcus.vance@aegissec.co.za',
    siteId: 'site-sandton',
    siteName: 'Regional Operations Center',
    companyId: 'comp-aegis',
    companyName: 'Aegis Elite Protection Services',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
  headoffice: {
    id: 'usr-exec-01',
    name: 'Dr. Sarah Ndlovu',
    role: 'headoffice',
    badgeNumber: 'EXEC-VP-02',
    phone: '+27 11 400 8800',
    email: 's.ndlovu@aegissec-group.com',
    siteId: 'site-sandton',
    siteName: 'Global Executive Command',
    companyId: 'comp-aegis',
    companyName: 'Aegis Elite Protection Services',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
  developer: {
    id: 'usr-dev-01',
    name: 'Lead Security Systems Engineer',
    role: 'developer',
    badgeNumber: 'DEV-ROOT-00',
    phone: '+27 82 000 9999',
    email: 'engineer@aegissec.dev',
    siteId: 'site-sandton',
    siteName: 'Core Platform Engineering',
    companyId: 'comp-aegis',
    companyName: 'Aegis Elite Protection Services',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
  },
};

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: 'inc-001',
    code: 'INC-2026-0842',
    title: 'Panic Alarm - Multi-Story Underground Parking P2',
    category: 'PANIC_GENERAL',
    status: 'responding',
    severity: 'critical',
    siteId: 'site-sandton',
    siteName: 'Sandton Financial Precinct & Mall',
    companyId: 'comp-aegis',
    houseId: 'hse-01',
    houseNumber: 'Unit 14',
    deviceId: 'dev-01',
    reporterId: 'usr-comm-01',
    reporterName: 'Nomsa Dlamini',
    reporterPhone: '+27 71 892 4110',
    reporterRole: 'community',
    coordinates: {
      lat: -26.1082,
      lng: 28.0573,
      accuracy: 6,
      address: 'Parking Bay P2-Yellow, Level -2, South Elevator Lobby',
      timestamp: Date.now() - 340000,
    },
    tracingActive: true,
    tracingHistory: [
      { lat: -26.1086, lng: 28.0578, timestamp: Date.now() - 340000 },
      { lat: -26.1084, lng: 28.0575, timestamp: Date.now() - 200000 },
      { lat: -26.1082, lng: 28.0573, timestamp: Date.now() - 60000 },
    ],
    assignedResponders: [
      {
        guardId: 'usr-guard-01',
        name: 'Officer Sipho Khumalo',
        callSign: 'Alpha-1 Response',
        etaMinutes: 2,
        currentCoords: { lat: -26.1065, lng: 28.0560 },
        status: 'en_route',
      },
      {
        guardId: 'usr-guard-02',
        name: 'Officer Tendai Moyo',
        callSign: 'Bravo-2 Mobile',
        etaMinutes: 4,
        currentCoords: { lat: -26.1098, lng: 28.0545 },
        status: 'en_route',
      },
    ],
    timeline: [
      {
        id: 't-1',
        timestamp: '14:22:10',
        action: 'Panic Button Triggered',
        actor: 'Nomsa Dlamini (Unit 14)',
        notes: 'Immediate high-frequency GPS tracing activated. Siren tone emitted.',
      },
      {
        id: 't-2',
        timestamp: '14:22:15',
        action: 'Dispatched Alert to Sandton Control Room',
        actor: 'System Automation',
        notes: 'Supervisor notified via priority audible alarm broadcast.',
      },
      {
        id: 't-3',
        timestamp: '14:23:01',
        action: 'Responders Assigned',
        actor: 'Supervisor Kagiso Sithole',
        notes: 'Dispatched Alpha-1 (Sipho) & Bravo-2 (Tendai) with tactical flashlights.',
      },
    ],
    notes: 'Caller heard footsteps and shattered glass near elevator shaft P2.',
    createdAt: '2026-08-23T14:22:10Z',
  },
  {
    id: 'inc-002',
    code: 'INC-2026-0841',
    title: 'Suspicious Vehicle Loitering at Delivery Gate 4',
    category: 'SUSPICIOUS_PERSON',
    status: 'triggered',
    severity: 'medium',
    siteId: 'site-sandton',
    siteName: 'Sandton Financial Precinct & Mall',
    companyId: 'comp-aegis',
    houseId: 'hse-04',
    houseNumber: 'Unit 03',
    deviceId: 'dev-06',
    reporterId: 'usr-guard-03',
    reporterName: 'Guard Lucas Sithole',
    reporterPhone: '+27 73 999 4411',
    reporterRole: 'guard',
    coordinates: {
      lat: -26.1055,
      lng: 28.0585,
      accuracy: 12,
      address: 'North Loading Dock Gate 4 Perimeter',
      timestamp: Date.now() - 900000,
    },
    tracingActive: false,
    tracingHistory: [],
    assignedResponders: [],
    timeline: [
      {
        id: 't-20',
        timestamp: '14:10:00',
        action: 'Guard Triggered Alarm',
        actor: 'Guard Lucas Sithole',
        notes: 'Silver sedan parked in restricted blind spot with engine running.',
      },
    ],
    notes: 'Registration plates partially obscured by mud.',
    createdAt: '2026-08-23T14:10:00Z',
  },
  {
    id: 'inc-003',
    code: 'INC-2026-0839',
    title: 'Medical Distress - Waterfront Promenade Cafe',
    category: 'MEDICAL_EMERGENCY',
    status: 'on_scene',
    severity: 'high',
    siteId: 'site-waterfront',
    siteName: 'V&A Marine & Retail Hub',
    companyId: 'comp-aegis',
    reporterId: 'usr-comm-02',
    reporterName: 'Brenda Jacobs',
    reporterPhone: '+27 82 444 1928',
    reporterRole: 'community',
    coordinates: {
      lat: -33.9062,
      lng: 18.4225,
      accuracy: 4,
      address: 'Pierhead Boardwalk, Near Clock Tower',
      timestamp: Date.now() - 1800000,
    },
    tracingActive: true,
    tracingHistory: [
      { lat: -33.9062, lng: 18.4225, timestamp: Date.now() - 1800000 },
    ],
    assignedResponders: [
      {
        guardId: 'usr-guard-04',
        name: 'First Aider Willem Coetzee',
        callSign: 'Medic-1 Marine',
        etaMinutes: 0,
        currentCoords: { lat: -33.9062, lng: 18.4225 },
        status: 'on_scene',
      },
    ],
    timeline: [
      {
        id: 't-31',
        timestamp: '13:55:00',
        action: 'Panic Alert Received',
        actor: 'Brenda Jacobs',
        notes: 'Elderly patron collapsed; CPR certified guard requested.',
      },
      {
        id: 't-32',
        timestamp: '13:58:30',
        action: 'Responder Arrived On Scene',
        actor: 'Medic-1 Willem Coetzee',
        notes: 'Administered AED defibrillator; Netcare 911 ambulance in route.',
      },
    ],
    notes: 'First Aid Kit #4 deployed from Dockmaster Station.',
    createdAt: '2026-08-23T13:55:00Z',
  },
];

export const INITIAL_CHECKPOINTS: Checkpoint[] = [
  {
    id: 'chk-01',
    siteId: 'site-sandton',
    siteName: 'Sandton Financial Precinct & Mall',
    companyId: 'comp-aegis',
    name: 'Main Atrium Entrance & Revolving Doors',
    zone: 'Zone A - Ground Level',
    code: 'AEGIS-CHK-SND-ZA01-ATRIUM',
    coordinates: { lat: -26.1074, lng: 28.0565 },
    requiredTimeWindowMinutes: 30,
    lastScannedAt: '2026-08-23T13:45:00Z',
    lastScannedBy: 'Officer Sipho Khumalo',
  },
  {
    id: 'chk-02',
    siteId: 'site-sandton',
    siteName: 'Sandton Financial Precinct & Mall',
    companyId: 'comp-aegis',
    name: 'P2 Underground Parking Fire Exit B',
    zone: 'Zone B - Basement P2',
    code: 'AEGIS-CHK-SND-ZB02-P2FIREB',
    coordinates: { lat: -26.1082, lng: 28.0573 },
    requiredTimeWindowMinutes: 45,
    lastScannedAt: '2026-08-23T12:30:00Z',
    lastScannedBy: 'Officer Sipho Khumalo',
  },
  {
    id: 'chk-03',
    siteId: 'site-sandton',
    siteName: 'Sandton Financial Precinct & Mall',
    companyId: 'comp-aegis',
    name: 'High Security Server Vault (Level 4)',
    zone: 'Zone C - Restricted Core',
    code: 'AEGIS-CHK-SND-ZC03-SERVERVAULT',
    coordinates: { lat: -26.1070, lng: 28.0558 },
    requiredTimeWindowMinutes: 60,
    lastScannedAt: '2026-08-23T13:10:00Z',
    lastScannedBy: 'Officer Tendai Moyo',
  },
  {
    id: 'chk-04',
    siteId: 'site-sandton',
    siteName: 'Sandton Financial Precinct & Mall',
    companyId: 'comp-aegis',
    name: 'North Perimeter Gate 4 & Loading Bay',
    zone: 'Zone D - External Perimeter',
    code: 'AEGIS-CHK-SND-ZD04-GATE4NORTH',
    coordinates: { lat: -26.1055, lng: 28.0585 },
    requiredTimeWindowMinutes: 20,
    lastScannedAt: '2026-08-23T14:05:00Z',
    lastScannedBy: 'Guard Lucas Sithole',
  },
  {
    id: 'chk-05',
    siteId: 'site-waterfront',
    siteName: 'V&A Marine & Retail Hub',
    companyId: 'comp-aegis',
    name: 'Dockside Fuel Storage & Jetty Point',
    zone: 'Marine Zone 1',
    code: 'AEGIS-CHK-VNA-MZ01-JETTY',
    coordinates: { lat: -33.9050, lng: 18.4210 },
    requiredTimeWindowMinutes: 30,
    lastScannedAt: '2026-08-23T13:30:00Z',
    lastScannedBy: 'Willem Coetzee',
  },
];

export const INITIAL_PATROL_SCANS: PatrolScan[] = [
  {
    id: 'scan-101',
    checkpointId: 'chk-01',
    checkpointName: 'Main Atrium Entrance & Revolving Doors',
    zone: 'Zone A - Ground Level',
    siteId: 'site-sandton',
    companyId: 'comp-aegis',
    guardId: 'usr-guard-01',
    guardName: 'Officer Sipho Khumalo',
    timestamp: '2026-08-23T13:45:12Z',
    coordinates: { lat: -26.1074, lng: 28.0565, accuracy: 5 },
    notes: 'All biometric turnstiles operational. No crowd accumulation.',
    status: 'verified',
  },
  {
    id: 'scan-102',
    checkpointId: 'chk-03',
    checkpointName: 'High Security Server Vault (Level 4)',
    zone: 'Zone C - Restricted Core',
    siteId: 'site-sandton',
    companyId: 'comp-aegis',
    guardId: 'usr-guard-02',
    guardName: 'Officer Tendai Moyo',
    timestamp: '2026-08-23T13:10:45Z',
    coordinates: { lat: -26.1070, lng: 28.0558, accuracy: 4 },
    notes: 'Dual keycard lock and Halon fire panel green.',
    status: 'verified',
  },
  {
    id: 'scan-103',
    checkpointId: 'chk-04',
    checkpointName: 'North Perimeter Gate 4 & Loading Bay',
    zone: 'Zone D - External Perimeter',
    siteId: 'site-sandton',
    companyId: 'comp-aegis',
    guardId: 'usr-guard-03',
    guardName: 'Guard Lucas Sithole',
    timestamp: '2026-08-23T14:05:30Z',
    coordinates: { lat: -26.1055, lng: 28.0585, accuracy: 8 },
    notes: 'Heavy delivery truck cleared. CCTV lens cleaned.',
    status: 'verified',
  },
];

export const INITIAL_OB_ENTRIES: OBEntry[] = [
  {
    id: 'ob-001',
    obNumber: 'OB 142/08/2026',
    siteId: 'site-sandton',
    siteName: 'Sandton Financial Precinct & Mall',
    companyId: 'comp-aegis',
    reporterId: 'usr-guard-01',
    reporterName: 'Officer Sipho Khumalo',
    reporterRole: 'guard',
    category: 'ACCESS_CONTROL',
    description: 'Contractor cleaning crew attempted entry after hours without valid pink permit slips. Advised site foreman to request supervisor sign-off before entering tenant floors.',
    timestamp: '2026-08-23T11:30:00Z',
    coordinates: { lat: -26.1074, lng: 28.0565, address: 'Service Entrance Gate B' },
    status: 'approved',
    supervisorSignature: 'Kagiso Sithole (Signed 11:45)',
    reviewedBy: 'Supervisor Kagiso Sithole',
    reviewedAt: '2026-08-23T11:45:00Z',
    attachments: [
      {
        type: 'photo',
        url: 'https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?w=400&auto=format&fit=crop&q=80',
        name: 'Contractor Badge Inspection.jpg',
      },
    ],
  },
  {
    id: 'ob-002',
    obNumber: 'OB 143/08/2026',
    siteId: 'site-sandton',
    siteName: 'Sandton Financial Precinct & Mall',
    companyId: 'comp-aegis',
    reporterId: 'usr-comm-01',
    reporterName: 'Nomsa Dlamini',
    reporterRole: 'community',
    category: 'PANIC_GENERAL',
    description: 'Suspicious individual tailgating residents into the private underground parking level P2. Smashed glass bottle heard near elevator shaft.',
    timestamp: '2026-08-23T14:22:00Z',
    coordinates: { lat: -26.1082, lng: 28.0573, address: 'Parking P2 Yellow Bay' },
    status: 'investigating',
    reviewedBy: 'Supervisor Kagiso Sithole',
    reviewedAt: '2026-08-23T14:24:00Z',
  },
  {
    id: 'ob-003',
    obNumber: 'OB 141/08/2026',
    siteId: 'site-waterfront',
    siteName: 'V&A Marine & Retail Hub',
    companyId: 'comp-aegis',
    reporterId: 'usr-guard-04',
    reporterName: 'Willem Coetzee',
    reporterRole: 'guard',
    category: 'MAINTENANCE_DEFECT',
    description: 'Saltwater corrosion detected on emergency lifebuoy release bracket near Berth 3. Work order logged with harbor engineering.',
    timestamp: '2026-08-23T09:15:00Z',
    coordinates: { lat: -33.9050, lng: 18.4210, address: 'Berth 3 Promenade' },
    status: 'approved',
    supervisorSignature: 'David Van Der Merwe (Signed 09:40)',
    reviewedBy: 'David Van Der Merwe',
    reviewedAt: '2026-08-23T09:40:00Z',
  },
];

export const INITIAL_EQUIPMENT: EquipmentItem[] = [
  {
    id: 'eq-001',
    serialNumber: 'MOT-DMR-8801',
    name: 'Motorola DMR Digital 2-Way Tactical Radio',
    category: 'Radio / Walkie',
    siteId: 'site-sandton',
    siteName: 'Sandton Financial Precinct & Mall',
    companyId: 'comp-aegis',
    status: 'issued',
    assignedTo: {
      userId: 'usr-guard-01',
      userName: 'Officer Sipho Khumalo',
      issuedAt: '2026-08-23T06:00:00Z',
      expectedReturnAt: '2026-08-23T18:00:00Z',
    },
    condition: 'Excellent',
    lastInspectionDate: '2026-08-20',
    batteryHealthPercent: 94,
  },
  {
    id: 'eq-002',
    serialNumber: 'AXN-BODY-402',
    name: 'Axon Body 3 HD Security Camera + GPS',
    category: 'Body Camera',
    siteId: 'site-sandton',
    siteName: 'Sandton Financial Precinct & Mall',
    companyId: 'comp-aegis',
    status: 'issued',
    assignedTo: {
      userId: 'usr-guard-01',
      userName: 'Officer Sipho Khumalo',
      issuedAt: '2026-08-23T06:00:00Z',
      expectedReturnAt: '2026-08-23T18:00:00Z',
    },
    condition: 'Excellent',
    lastInspectionDate: '2026-08-21',
    batteryHealthPercent: 88,
  },
  {
    id: 'eq-003',
    serialNumber: 'GAR-WAND-109',
    name: 'Garrett SuperScanner V Handheld Metal Detector',
    category: 'Metal Detector',
    siteId: 'site-sandton',
    siteName: 'Sandton Financial Precinct & Mall',
    companyId: 'comp-aegis',
    status: 'available',
    condition: 'Good',
    lastInspectionDate: '2026-08-22',
    batteryHealthPercent: 100,
  },
  {
    id: 'eq-004',
    serialNumber: 'VEST-LVL3A-992',
    name: 'Level IIIA Tactical Kevlar Ballistic Vest',
    category: 'Ballistic Vest',
    siteId: 'site-sandton',
    siteName: 'Sandton Financial Precinct & Mall',
    companyId: 'comp-aegis',
    status: 'issued',
    assignedTo: {
      userId: 'usr-guard-02',
      userName: 'Officer Tendai Moyo',
      issuedAt: '2026-08-23T06:00:00Z',
      expectedReturnAt: '2026-08-23T18:00:00Z',
    },
    condition: 'Good',
    lastInspectionDate: '2026-08-15',
  },
  {
    id: 'eq-005',
    serialNumber: 'FL-OLIGHT-77',
    name: 'Olight Warrior X 3 Turbo 2500-Lumen Torch',
    category: 'Flashlight',
    siteId: 'site-sandton',
    siteName: 'Sandton Financial Precinct & Mall',
    companyId: 'comp-aegis',
    status: 'maintenance',
    condition: 'Fair',
    lastInspectionDate: '2026-08-22',
    batteryHealthPercent: 42,
  },
  {
    id: 'eq-006',
    serialNumber: 'SAM-TAC-PH-09',
    name: 'Samsung XCover Rugged Patrol Phone (NFC/QR)',
    category: 'Patrol Phone',
    siteId: 'site-sandton',
    siteName: 'Sandton Financial Precinct & Mall',
    companyId: 'comp-aegis',
    status: 'available',
    condition: 'Excellent',
    lastInspectionDate: '2026-08-23',
    batteryHealthPercent: 97,
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-01',
    companyId: 'comp-aegis',
    timestamp: '2026-08-23 14:23:01',
    actor: 'Supervisor Kagiso Sithole',
    actorRole: 'supervisor',
    action: 'DISPATCH_RESPONDERS',
    details: 'Assigned Alpha-1 (Sipho Khumalo) to INC-2026-0842',
  },
  {
    id: 'aud-02',
    companyId: 'comp-aegis',
    timestamp: '2026-08-23 14:22:10',
    actor: 'Nomsa Dlamini',
    actorRole: 'community',
    action: 'PANIC_TRIGGERED',
    details: 'Emergency beacon triggered with real-time GPS coordinates (-26.1082, 28.0573)',
  },
  {
    id: 'aud-03',
    companyId: 'comp-aegis',
    timestamp: '2026-08-23 13:45:12',
    actor: 'Officer Sipho Khumalo',
    actorRole: 'guard',
    action: 'PATROL_QR_SCANNED',
    details: 'Verified checkpoint AEGIS-CHK-SND-ZA01-ATRIUM at Main Atrium Entrance',
  },
  {
    id: 'aud-04',
    companyId: 'comp-aegis',
    timestamp: '2026-08-23 11:45:00',
    actor: 'Supervisor Kagiso Sithole',
    actorRole: 'supervisor',
    action: 'OB_ENTRY_APPROVED',
    details: 'Digitally signed and approved OB entry OB 142/08/2026',
  },
  {
    id: 'aud-05',
    companyId: 'comp-aegis',
    timestamp: '2026-08-23 06:00:00',
    actor: 'Elena Rostova',
    actorRole: 'admin',
    action: 'EQUIPMENT_ISSUED',
    details: 'Issued Radio MOT-DMR-8801 to Officer Sipho Khumalo for Day Shift',
  },
];
